import useTitle from "../hooks/useTitle";
import Accordion from "../components/Accordion";

const QNA = () => {
  useTitle("QNA");

  return (
    <div className="mt-[104px] lg:mt-[144px] mb-10 lg:mb-20 section-wrapper">
      <Accordion
        title="What is the role of the catalytic converter in a car's exhaust system?"
        content="
        The catalytic converter is a crucial component in a car's exhaust system. Its main role is to convert harmful pollutants in the exhaust gases, such as carbon monoxide, nitrogen oxides, and hydrocarbons, into less harmful substances like carbon dioxide, nitrogen, and water vapor. This conversion is facilitated by a catalyst inside the converter, usually made of platinum, palladium, and rhodium."
      />
      <Accordion
        title="How does an electric car differ from a traditional gasoline-powered car?"
        content="Electric cars use electric motors powered by rechargeable batteries, while traditional gasoline-powered cars rely on internal combustion engines fueled by gasoline. Electric cars produce zero tailpipe emissions, making them more environmentally friendly. They also have different maintenance needs and charging requirements compared to traditional cars."
      />
      <Accordion
        title="What is the purpose of the transmission in a vehicle, and how do automatic and manual transmissions differ?"
        content="The transmission in a vehicle is responsible for controlling the power generated by the engine and transmitting it to the wheels. Automatic transmissions shift gears automatically, while manual transmissions require the driver to manually engage and disengage gears using a clutch pedal and gear shift. Each type has its advantages, with automatic transmissions offering convenience and manual transmissions providing more control for some drivers."
      />
      <Accordion
        title="Explain the concept of ABS (Anti-lock Braking System) in cars and its importance."
        content="ABS is a safety feature in cars designed to prevent wheel lockup during braking, maintaining steering control and preventing skidding. It works by modulating brake pressure individually to each wheel based on sensor input. ABS is crucial for improving vehicle stability during emergency braking situations, reducing the risk of accidents and enhancing overall braking performance."
      />
      <Accordion
        title="What is the significance of engine oil in a car, and why is regular oil change important?"
        content="
        Engine oil plays a vital role in lubricating and cooling the engine components, reducing friction, and preventing wear. Regular oil changes are essential to maintain proper engine function, prevent sludge buildup, and extend the engine's lifespan. It also contributes to fuel efficiency and overall vehicle performance."
      />
      <Accordion
        title="What are the key benefits of using synthetic motor oil in a car?"
        content="
        Synthetic motor oil offers several advantages over conventional oil, including better temperature stability, improved viscosity in extreme conditions, and enhanced engine protection. It also helps reduce friction, provides superior wear protection, and can extend the time between oil changes compared to conventional oils."
      />
      <Accordion
        title="Explain the concept of hybrid vehicles and how they combine electric and gasoline power."
        content="
        Hybrid vehicles utilize both an internal combustion engine fueled by gasoline and an electric motor powered by a battery. The hybrid system intelligently switches between the two power sources based on driving conditions to optimize fuel efficiency. This combination allows for lower emissions, increased fuel economy, and the ability to operate in electric-only mode at lower speeds."
      />
      <Accordion
        title="What are the common signs of a failing car battery, and how often should it be replaced?"
        content="
        Signs of a failing car battery include slow engine cranking, dimming headlights, and difficulty starting the vehicle. The lifespan of a car battery can vary, but on average, it may need replacement every 3 to 5 years. Regular battery checks and maintenance can help identify issues early and ensure reliable vehicle starting."
      />
    </div>
  );
};

export default QNA;
